name: core_ui

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  # UI - Widgets.
  flash: ^3.0.5+1

  # Icons.
  font_awesome_flutter: ^10.5.0
