name: free_file

packages:
  - apps/*
  - core_packages/*
  - modules/*
  - packages/*

scripts:
  gen:
    run: melos exec --scope="core_ui" -- fluttergen

  build-macos:
    run: melos exec --scope="ff_desktop" -- flutter build macos
