name: local_entity_provider

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core_packages/core
  utils:
    path: ../../packages/utils

  path_provider: ^2.1.4
  win32: ^5.7.1
