name: theme

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  storage:
    path: ../../packages/storage
  utils:
    path: ../../packages/utils

  system_theme: ^2.3.1
