name: ff_desktop
description: Free File Explorer

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core_packages/core
  core_ui:
    path: ../../core_packages/core_ui
  theme:
    path: ../../core_packages/theme

  storage:
    path: ../../packages/storage
  utils:
    path: ../../packages/utils

  local_entity_provider:
    path: ../../modules/local_entity_provider

  # Localization.
  intl: 0.18.1
  flutter_localizations:
    sdk: flutter

  # State Management.
  flutter_riverpod: ^2.4.3

  # Navigation.
  go_router: ^11.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
flutter:

  uses-material-design: true

  assets:
    - assets/
