name: ff_desktop
description: Free File Explorer

publish_to: 'none'

version: 0.3.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core_packages/core
  core_ui:
    path: ../../core_packages/core_ui
  theme:
    path: ../../core_packages/theme

  storage:
    path: ../../packages/storage
  utils:
    path: ../../packages/utils

  local_entity_provider:
    path: ../../modules/local_entity_provider
  shortcut:
    path: ../../modules/shortcut

  # Localization.
  intl: 0.19.0
  flutter_localizations:
    sdk: flutter

  # Navigation.
  go_router: ^14.3.0

  # UI - Platform.
  flutter_acrylic: ^1.1.4
  bitsdojo_window: ^0.1.6
  desktop_lifecycle: ^0.1.1
  desktop_multi_window: ^0.2.0
  macos_window_utils: ^1.5.0
  pasteboard: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/themes/

flutter_gen:
  output: lib/constants/generated/
  line_length: 80
